### PR TITLE
Feature/per sublayer filtering

### PR DESCRIPTION
**Pull request by nerik**
Flag setting is now per layer, including in the workspace.
Check with Skytruth for the implications of this.
Note: there are no UI elements to filter per layer yet, and the former flag selector is not working anymore for the moment.

### CODE REVIEW

**Comment by nerik** [comment]
gfw-double

**Comment by nerik** [comment]
Task added to PT : https://www.pivotaltracker.com/story/show/137370875
"Heatmap sublayers should be able to share the same tile data"

**Comment by andresgnlez** [comment]
Looks good!

**Comment by nerik** [comment]
🎄

**Pull request merged**
