### PR TITLE
Fix filter for Andorra case

### PR DESCRIPTION
**Pull request by tiagojsag**

### CODE REVIEW

**Comment by nerik** [comment]
It's `isNaN` that you were looking for.
But having NaN in the first place was weird, so I fixed that and used an explicit `===undefined` (because 0, Andorra's code, is falsy, yippeee JS)

**Comment by tiagojsag** [comment]
I tried the NaN comparison, didn't work. anyway, I trust your js skills more than mine, so as long as the bug is fixed, I'm happy

**Comment by nerik** [comment]
It should, and also, `isInteger` is not supported by IE.

**Comment by nerik** [comment]
Oh and FYI, in JS:
```
NaN === NaN
false
```
:p

**Pull request merged**
