### PR TITLE
Analytics

### PR DESCRIPTION
**Pull request by nerik**

### CODE REVIEW

**Comment by nerik** [comment]
@tiagojsag please make sure that the client is aware that this is only loaded once (SPA). If they want per-page analytics this is gonna need some more work from us.

**Comment by tiagojsag** [comment]
then we need to do that work :S

**Comment by nerik** [comment]
@tiagojsag GA is implemented. Please ask the client for their tracking code and add it to GA_TRACKING_CODE env.

**Comment by nerik** [comment]
Also, this can be merged as is.

**Comment by tiagojsag** [comment]
Looks good - only need documentation for the new env var on the readme, then you can merge

**Pull request merged**
