### PR TITLE
Remove map events properly

### PR DESCRIPTION
**Pull request by andresgnlez**

### CODE REVIEW

**Comment by andresgnlez** [comment]
When `componentWillUnmount` triggers are removes all events attached to map, once you try to go back to the map nothing happens on it. This "feature" seems to be there always but until now, due to the current error (function not found) this didn't happen.

**Comment by nerik** [comment]
I wasn't aware you couldn't use removeListener directly, thanks.
I'm looking at this now.

**Comment by nerik** [comment]
So it turns out you can remove all listeners at once with `clearInstanceListeners`.
The actual problem, the vessels layer not loading the second time you visit the map, is not related to this. I will fix it in https://github.com/Vizzuality/GlobalFishingWatch/pull/434

**Comment by andresgnlez** [comment]
@nerik That's it. I saw that method but I wasn't very sure to use it because with that your are removing ALL events of the instanced map and IMHO maybe this is not the best place to do that (I would only remove the polygon-related events) but if you find there's no problem with this. Go ahead 😁

**Pull request merged**
