### PR TITLE
Reporting

### PR DESCRIPTION
**Pull request by nerik**

### CODE REVIEW

**Comment by nerik** [comment]
report

**Comment by nerik** [comment]
For now only works with the MPA- no take layer, as I prepared it on my Carto account in advance

**Comment by tiagojsag** [comment]
I'm wondering if it makes sense to auto-close the tooltip after you press "add to report". Your opinion @nerik ?

**Comment by nerik** [comment]
@tiagojsag I don't think so, keeping the tooltip opened helps the user understand the "added to report/removed from report" mechanism.
@danielcasius ?

**Comment by tiagojsag** [comment]
yes, I see the value in that. However, as I tested, I ended up closing that modal right after, every time. Since the remove interaction is also duplicated between the tooltip and the layer list on the bottom right, I am not sure if it's worth leaving it open. But yeah @danielcasius can decide for us

**Comment by danielcasius** [comment]
Let's try not closing the tooltip, letting the user know the "Added to report" status. This tooltip should be closed by clicking anywhere on the map, to be a non-intrusive element.

**Comment by nerik** [comment]
@tiagojsag Dani's feedback included, it's ready to be merged

**Pull request merged**
