### PR TITLE
fix accordions issues

### PR DESCRIPTION
**Pull request by nerik**
screen shot 2016-09-01 at 11 55 48

### CODE REVIEW

**Comment by tiagojsag** [comment]
- [ ] The animation is a bit "bumpy".
- [ ] The arrow does not turn to the original position when closing the element

**Comment by nerik** [comment]
I fixed above issues by completely removing react-sanfona.
I left the dependencies and the css on index.html because our map will still use those - eventually they should be removed too (I´ll create a pivotal task)

**Comment by tiagojsag** [comment]
on FAQ, when you open the first question, it auto scrolls (do we want this) and it scrolls to the beginning of the answer, not the question.

**Comment by tiagojsag** [comment]
seems like clicking on an open question to close it is not working

**Comment by nerik** [comment]
Should be all good now.

**Comment by clementprdhomme** [comment]
I have two small requests:
* On the FAQ, when clicking on an item from one section to another, I have to click twice in order to open it. Could you change that?
* Could you just add one-line comments regarding the props of the components?

Once the conflicts are fixed and if Tiago is happy about the feature, let's merge it 😄.

**Pull request merged**
