### PR TITLE
Pinned Vessels UI

### PR DESCRIPTION
**Pull request by andresgnlez**
Mergeable!

### CODE REVIEW

**Comment by nerik** [comment]
@andresgnlez could you make this point to `mapster` and rebase if needed please?

**Comment by andresgnlez** [comment]
@nerik sure

**Comment by nerik** [comment]
I think you should cherry pick your 2 commits in a new branch :/

**Comment by andresgnlez** [comment]
Rebased in https://github.com/Vizzuality/GlobalFishingWatch/pull/466

**Pull request closed without merging**
