### PR TITLE
Timeline

### PR DESCRIPTION
**Pull request by tiagojsag**
Timeline

### CODE REVIEW

**Comment by tiagojsag** [comment]
Seems we are still missing a way to manipulate start and end dates - could you add inputs for it, please?

**Comment by apercas** [comment]
Yes, but the logic is ready to change the default values by others inputed by the user. Could we merge it and keep working from here? Otherwise the differences between master (from where we're starting the branches) and this one are going to be really big and difficult to deal with @tiagojsag

**Comment by tiagojsag** [comment]
if @davidsingal approves, feel free to merge

**Comment by davidsingal** [comment]
Yeah, it is ok! 👍

**Pull request merged**
