### PR TITLE
Removes the duplicates styles

### PR DESCRIPTION
**Pull request by clementprdhomme**
Previously, all the styles would be duplicated due to multiple imports. This PR solves it by:
* removing the reference to `styles.css` inside the HTML file as it is automatically included by webpack
* removing the import of `base.scss` in `index.scss` as it is already imported in `application.scss`

Note: `index.scss` should be entirely removed as the styles for each component should be imported via webpack/JS but I left them untouched to prevent breaking anything at the moment. I'll add a task to Pivotal.

### CODE REVIEW

**Comment by tiagojsag** [comment]
Our map looks pretty epic with this

**Comment by nerik** [comment]
@tiagojsag @clementprdhomme keeping the reference to base.scss left everything intact. I don't think keeping multiple refs to the same scss files don't matter anyway, because the sass compiler will not duplicate styles.

**Comment by clementprdhomme** [comment]
We still have duplicates for the base styles 😕.

**Comment by nerik** [comment]
This last commit:
- removes duplicated global styles (removes global styles loaeded at react component level)
- removes index.scss
- puts all global styles in a file that is loaded once
- removes that ugly div > div > div trick in base.scss

I was careful not to introduce any regressions in the styles (including in the map), but it's worth double checking. @clementprdhomme would you please have a look at this? Thanks :)

**Comment by hectoruch** [comment]
Something is wrong on responsive styles here.

image

**Comment by nerik** [comment]
Thanks @hectoruch, good catch.

**Comment by clementprdhomme** [comment]
I haven't experienced any issue so far. Is it ready to merge?

**Pull request merged**
