### PR TITLE
update menu styles and fix errors dropwdown

### PR DESCRIPTION
**Pull request by hectoruch**
update menu styles and fix errors dropwdown

### CODE REVIEW

**Comment by tiagojsag** [comment]
tested and it looks ok. @hectoruch did you run js and sass linters? @clementprdhomme can you review please?

**Comment by clementprdhomme** [comment]
Hey @hectoruch,

I would like to see two changes before merging it:

1. In the menu, under the news item, the "Articles and Publications" one has a huuge line-space. Could you modify it according to the design?
2. In `_settings.css`, the media queries are stored into variables. The idea is to enforce the developers to use the mobile-first approach and by this, I mean that instead of using `@media screen and (min-width: $breakpoint-tablet)`, you should use `@media #{$mq-tablet}`.

**Comment by clementprdhomme** [comment]
Also, as @tiagojsag said, there are some eslint/sass-lint errors you could fix.

**Comment by hectoruch** [comment]
I fix the media queries and the line-space on menu. And also fix slint issues.
@clementprdhomme @tiagojsag

**Comment by clementprdhomme** [comment]
@tiagojsag, I did a major refactor of the CSS file. Can you review everything's still working well?
Please note it doesn't make the header work on mobile: the styles are responsive but further work is needed in order to make the mobile menu appear.

@hectoruch, let's talk tomorrow about how you could have done the CSS from the beginning so we won't have to rewrite part of your work in the future. I took some notes so I can give you example.
Bring your 🎒, tomorrow is 🏫 day.

**Comment by tiagojsag** [comment]
dropdowns are larger than before.

**Pull request merged**
