### PR TITLE
Fix/tooltip again

### PR DESCRIPTION
**Pull request by nerik**
https://www.pivotaltracker.com/story/show/129783519

### CODE REVIEW

**Comment by clementprdhomme** [comment]
* I don't know if it's just on iOS, but when closing once the tooltip, and opening it again, I can't close it anymore.
* Could we just close it by touching somewhere else? It would be like attaching an event to the body or the document.

**Comment by nerik** [comment]
Sorry, I was home and couldn't test this on an actual device, looking at this now.

**Comment by clementprdhomme** [comment]
@hectoruch Could you review that?

On desktop, the tooltip should appear as if we were using the CSS's hover state. On Mobile, the tooltip must appear on click, disappear if clicking again (but not on the tooltip itself) or if clicking elsewhere on the page.

**Comment by hectoruch** [comment]
Tested on:

- Firefox
- Chrome
- Edge
- Internet Explorer 11
- Safari
- IOS
- Android

Works great! Ready to merge.

**Pull request merged**
