### PR TITLE
Feature/timeline

### PR DESCRIPTION
**Pull request by apercas**
Pretty basic timeline. WIP, but mergeable.
timeline

### CODE REVIEW

**Comment by apercas** [comment]
Updated with clickable timeline.

**Comment by davidsingal** [comment]
It looks very good, the code is very good too. Please avoid to use var with ES6.

**Comment by apercas** [comment]
@davidsingal Updated :)

**Comment by tiagojsag** [comment]
There seems to be a difference in scope between `var` and `let`, please test stuff ;)

**Comment by apercas** [comment]
Sure, everything is working as smooth as it did before.

**Pull request merged**
