### PR TITLE
fix responsive and desktop footer styles

### PR DESCRIPTION
**Pull request by hectoruch**

### CODE REVIEW

**Comment by tiagojsag** [comment]
looks good ;)
A small thing: we need to review the breakpoint for the logos. At 1030px +- the 4 logos are all together, which might cause problems

**Comment by clementprdhomme** [comment]
Seems ok. What do you think @tiagojsag?

**Comment by clementprdhomme** [comment]
It's related to this task: https://www.pivotaltracker.com/story/show/129622325

**Comment by tiagojsag** [comment]
Under 770px width, is it possible ot move the LDF logo more to the right?

**Comment by hectoruch** [comment]
@tiagojsag I just change it

**Comment by tiagojsag** [comment]
Functionally it looks perfect now. @hectoruch please clean up that commented code, otherwise can be merged if @clementprdhomme says so

**Pull request merged**
