### PR TITLE
added North Star basemap

### PR DESCRIPTION
**Pull request by nerik**
fishing-northstar

fishing-northstar-2

### CODE REVIEW

**Comment by tiagojsag** [comment]
Let's run this by Enrique and/or Paul, and if they like it, we need to move it to their mapbox account

**Comment by nerik** [comment]
Note that we are already using other Mapbox basemaps (with Dani's token)
The question is : do we make this a default?

**Comment by danielcasius** [comment]
It looks amazing. Great job, @nerik !

**Comment by tiagojsag** [comment]
The other basemaps point to enrique's account. If we are indeed using Dani's account, we should not

**Comment by nerik** [comment]
Ah my bad, it's not the same token

**Comment by tiagojsag** [comment]
@enriquetuya this is part of the new design iteration, but since it's already implemented, we can deploy it as soon as we want - we just need to export to you Mapbox account and change the URL. Let me know how you wish to proceed

**Comment by tiagojsag** [comment]
https://basecamp.com/1756858/projects/12049853/todos/319956461

**Pull request merged**
